### ISSUE TITLE
How can this be applied to Nuxt3?

### ISSUE THREAD

**Issue by letzfets** [posva/vue-router-view-transition#2]
The demo seems quite old - I'm getting this error:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (<..path>/vue-router-view-transition/node_modules/webpack/lib/util/createHash.js:135:53)
```

I'd like to apply the delay in the route to a Nuxt 3 project, where I use navigateTo() from one page to another. The *landing page* has a transition in it, so it can't scroll to the content of these elements with #hash-based navigation until that transition is finished. How can I therefore apply this package to Nuxt3? Or is there anything newer available?

**Comment by posva** [comment]
By putting it into a Nuxt plugin. Note this is Vue 2 only though

**Comment by lizyChy0329** [comment]
Why not have a vue3 version? Is there no such need for?
